import jwt
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from rest_framework import authentication, exceptions

User = get_user_model()

class SupabaseJWTAuthentication(authentication.BaseAuthentication):
    """
    Custom authentication class for Django REST Framework that verifies 
    JWT tokens generated by local Supabase Auth (GoTrue).
    """
    def authenticate(self, request):
        auth_header = request.headers.get('Authorization')
        if not auth_header:
            return None
            
        parts = auth_header.split()
        if len(parts) != 2 or parts[0].lower() != 'bearer':
            return None
            
        token = parts[1]
        try:
            # Decode token using PyJWT and the shared JWT Secret
            payload = jwt.decode(
                token, 
                settings.SUPABASE_JWT_SECRET, 
                algorithms=['HS256'], 
                options={"verify_aud": False}  # Bypass strict audience checks for local flexibility
            )
        except jwt.ExpiredSignatureError:
            raise exceptions.AuthenticationFailed('Token has expired')
        except jwt.InvalidTokenError:
            raise exceptions.AuthenticationFailed('Invalid token')
            
        user_id = payload.get('sub')
        email = payload.get('email')
        
        if not user_id:
            raise exceptions.AuthenticationFailed('Invalid token payload: missing sub')
            
        # Look up user. If user doesn't exist by username (Supabase UUID), check by email
        user = User.objects.filter(username=user_id).first()
        if not user:
            # Check if a placeholder user exists with this email (e.g. created during task sharing)
            if email:
                user = User.objects.filter(email__iexact=email).first()
                if user:
                    # Update username to the Supabase UUID
                    try:
                        user.username = user_id
                        user.save()
                    except IntegrityError:
                        user = User.objects.get(username=user_id)
            
            # If no placeholder was found, create a new user record
            if not user:
                try:
                    user = User.objects.create(username=user_id, email=email or '')
                except IntegrityError:
                    user = User.objects.get(username=user_id)
        elif email and user.email != email:
            # Update the email in our Django model if it changed in Supabase
            user.email = email
            user.save()
            
        return (user, None)
